### ISSUE TITLE
Adding Temp Sensor and Different modes as well as silent button

### ISSUE THREAD

**Issue by devium335** [zyonse/homebridge-dreo#18]
Adding support for the temperature sensor as a temp sensor and different modes such as sleep, auto etc and support for the silent button make everything a button including oscillating

**Comment by alvst** [comment]
Temperature, assuming it's returned by the api, should be an easy add. HomeKit, surprisingly, does not support different modes so that's not possible in a way done well.

**Comment by alvst** [comment]
Based on my review of the HA code, temperature does seem to be returned by the api. I'll take a look and see if I can get it added to this one via a PR.

**Comment by zyonse** [comment]
The websocket connection reports the temperature sensor state so that should be feasible to implement. I agree with @alvst that the modes would be difficult to implement in a clean way. Though I could add a toggle to the config to just permanently mute the fan if that's something people would be interested in.

**Comment by zyonse** [comment]
The reason I didn't initially implement the temp sensor is because I've found it to be inaccurate.

**Comment by alvst** [comment]
Yes that makes sense. I find the temp sensor in my dreo to be 2-3 degrees, sometimes more, higher than my other temperature sensors say.

**Comment by devium335** [comment]
maybe adjust it down by 2-3 degrees or asking the user in home bridge setup optionally the difference in temp then adding it later?

**Comment by alvst** [comment]
Took me a while because I forgot about this but I've created a [pull request](https://github.com/zyonse/homebridge-dreo/pull/19) with the temperature sensor added as well as the offset and ability to show/hide the temperatures sensors. for simplicity, if you have multiple fans, you can't show/hide individual temperature sensors, but you can always hide those within the home app.

**Comment by devium335** [comment]
Thank You!

**Comment by RadDip** [comment]
Version 3.2 with Temp sensor is off significantly in homekit compared to what it is in the Dreo app.   So my Deep app is reading 68 degrees F and Homekit is reading 154 degrees F

**Comment by dfinstein** [comment]
> Version 3.2 with Temp sensor is off significantly in homekit compared to what it is in the Dreo app. So my Deep app is reading 68 degrees F and Homekit is reading 154 degrees F

I’m having a similar issue. My Dreo fan temp sensor is showing 100 degrees Fahrenheit higher than the actual reading in the Dreo app. This is new behavior in 3.2.

**Comment by alvst** [comment]
The conversion between Celsius and Fahrenheit is off. I submitted a fix yesterday waiting on approval.
