### ISSUE TITLE
region detection

### ISSUE THREAD

**Issue by chloke** [zyonse/homebridge-dreo#4]
Hey, sorry for not answering your last request on time.
I just tested it and saw the reason for the error in the log.
The problem is that your code adds the country code to the url instead of the region.
For example I live in Germany so my country code is DE. The url your plugin is trying to connect to is now app-api-de.dreo-cloud.com
but every dreo account in a country in Europe shares the same url which is  app-api-eu.dreo-cloud.com.
So the current region detection code won't work unfortunately.
I guess the easiest solution would be to check if a connection to the us servers is successful, if not use the eu url, regardless of the country code.

**Comment by NTK421** [comment]
What's going on with this issue. I'm having the same error when starting the plugin. I'm in the UK

**Comment by czitooo** [comment]
With respect for having this plugin available at all... for a 'verified' plugin this really should have been sorted by now since it's a fairly simple fix. 
I'm also in the UK and changing the region to 'eu' manually (eg. 'app-api-eu.dreo-cloud.com') works instantly by going into the code, as mentioned by @chloke 
The best fix surely is just let the user select the correct region upon setup since many countries are grouped together?

**Comment by NTK421** [comment]
I saw the fix but I'm not talented enough for coding unless there's step by step instructions. I'm just a simple plumber trying to create a full smart home and would love to have the Dreo fan on HomeKit so I can set automations for my baby daughter so she doesn't get too hot or cold. I bought the fan due to the fact that this plugin was verified to work. Now the fan is an excellent fan in its own right but if two capable people have figured out the issue why hasn't the creator fixed said issue and released an update for us less capable people.

**Comment by zyonse** [comment]
I took another look at the API calls that the app makes when connecting to the Dreo servers, and it looks like the app keeps an internal list of what countries/regions are assigned to each server. Going to try to implement similar logic in the plugin.

Also let's try to keep the comments constructive here.

**Comment by zyonse** [comment]
@czitooo Can you test the code I just pushed?

**Comment by daveramirez5** [comment]
It worked for me from Mexico

**Comment by NTK421** [comment]
Worked for me perfectly in the UK

**Comment by czitooo** [comment]
@zyonse Works perfectly, nicely done 👍
